
test('Our first test', () => {
    throw new Error('Test not passed!');
});